name: Supercharge tests

on: [workflow_dispatch, push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Composer dependencies
        run: composer install
        working-directory: framework/core

      - name: Install Composer dependencies
        run: composer install

      - name: Run tests
        run: vendor/bin/supercharge phpunit --directory=framework/core -c tests/phpunit.integration.xml
